# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
fi

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Bash helper functions
if [ -f ~/.bash_helpers ]; then
    . ~/.bash_helpers
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PATH="$PATH:$HOME/bin/apache-ant-1.9.6/bin:$HOME/bin/Qt5.5.1/5.5/gcc_64/bin:$HOME/bin/android-sdk-linux/tools:$HOME/bin/android-sdk-linux/platform-tools"
export ANT_HOME="$PATH:$HOME/bin/apache-ant-1.9.6"
export ANDROID_HOME="/home/drugsha/bin/android-sdk-linux"

# Enable 256 colors for terminal
export TERM=xterm-256color

# added by Anaconda2 2.4.0 installer
export PATH="/home/drugsha/anaconda2/bin:$PATH"

# fix CURL certificates path
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# TexLive
export PATH=/usr/local/texlive/2016/bin/x86_64-linux:$PATH

export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting

OCLINT_HOME=~/bin/oclint-0.11
export PATH=$OCLINT_HOME/bin:$PATH
